/* eslint-disable @typescript-eslint/no-deprecated -- tseslint.config() is the only way to use extends; core defineConfig has incompatible API */
import { includeIgnoreFile } from "@eslint/config-helpers";
import eslint from "@eslint/js";
import eslintPluginPrettier from "eslint-plugin-prettier/recommended";
import eslintPluginAstro from "eslint-plugin-astro";
import pluginReact from "eslint-plugin-react";
import reactCompiler from "eslint-plugin-react-compiler";
import eslintPluginReactHooks from "eslint-plugin-react-hooks";
import path from "node:path";
import tseslint from "typescript-eslint";

const gitignorePath = path.resolve(import.meta.dirname, ".gitignore");

const baseConfig = tseslint.config({
  extends: [eslint.configs.recommended, tseslint.configs.strictTypeChecked, tseslint.configs.stylisticTypeChecked],
  languageOptions: {
    parserOptions: {
      projectService: true,
      tsconfigRootDir: import.meta.dirname,
    },
  },
  rules: {
    "no-console": "warn",
    "no-unused-vars": "off",
    "@typescript-eslint/no-unused-vars": [
      "error",
      {
        argsIgnorePattern: "^_",
        varsIgnorePattern: "^_",
        caughtErrorsIgnorePattern: "^_",
        destructuredArrayIgnorePattern: "^_",
        ignoreRestSiblings: true,
      },
    ],
    "@typescript-eslint/restrict-template-expressions": ["error", { allowNumber: true }],
    "@typescript-eslint/no-misused-promises": ["error", { checksVoidReturn: { attributes: false } }],
  },
});

const reactConfig = tseslint.config({
  files: ["**/*.{js,jsx,ts,tsx}"],
  extends: [pluginReact.configs.flat.recommended],
  languageOptions: {
    ...pluginReact.configs.flat.recommended.languageOptions,
    globals: {
      window: true,
      document: true,
    },
  },
  plugins: {
    "react-hooks": eslintPluginReactHooks,
    "react-compiler": reactCompiler,
  },
  settings: { react: { version: "detect" } },
  rules: {
    ...eslintPluginReactHooks.configs.recommended.rules,
    "react/react-in-jsx-scope": "off",
    "react-compiler/react-compiler": "error",
  },
});

// ---------------------------------------------------------------------------
// Runtime boundary (S-01, extended for F-03)
// ---------------------------------------------------------------------------
// This project builds for TWO runtimes. The Astro app targets Cloudflare workerd; the
// pipeline worker (`npm run collect`) is plain Node and uses Node-oriented dependencies
// such as rss-parser and @anthropic-ai/sdk. An import crossing the boundary breaks a build —
// and would break it in whichever slice happens to add the import, far from where the rule
// was understood. These rules make the split structural rather than remembered.
const runtimeBoundaryConfig = tseslint.config(
  {
    // App -> worker: pulling collection/LLM code into a page or island drags Node built-ins
    // into the workerd bundle.
    files: ["src/pages/**", "src/components/**", "src/layouts/**", "src/middleware.ts"],
    rules: {
      "no-restricted-imports": [
        "error",
        {
          patterns: [
            {
              group: ["@/lib/collection/*", "@/lib/collection", "@/lib/llm/*", "@/lib/llm", "@/worker/*", "@/worker"],
              message:
                "Worker-side code runs in plain Node and must not enter the Astro/workerd bundle. " +
                "If a page needs pipeline data, read it from the database instead.",
            },
          ],
        },
      ],
    },
  },
  {
    // Worker -> app: `astro:env/server` is a Vite virtual module that exists only inside
    // Astro's build and fails to resolve under Node.
    files: ["src/worker/**", "src/lib/collection/**", "src/lib/llm/**"],
    rules: {
      "no-restricted-imports": [
        "error",
        {
          paths: [
            {
              name: "astro:env/server",
              message:
                "astro:env/server is an Astro build-time virtual module and does not resolve in Node. " +
                "Worker code reads configuration through src/worker/env.ts.",
            },
          ],
          patterns: [
            {
              group: ["@/lib/supabase-admin", "@/lib/supabase"],
              message:
                "These modules import astro:env/server, which does not resolve in Node. " +
                "Build the client with createServiceClient() from @/lib/supabase-service instead.",
            },
          ],
        },
      ],
      // The worker is a CLI: printing what it did is its interface, not a debug leftover.
      "no-console": "off",
    },
  },
);

const astroConfig = tseslint.config({
  files: ["**/*.astro"],
  rules: {
    "astro/no-set-html-directive": "error",
    "astro/no-unused-css-selector": "warn",
    "astro/prefer-class-list-directive": "warn",
  },
});

export default tseslint.config(
  includeIgnoreFile(gitignorePath),
  // Generated Supabase types — regenerated by `supabase gen types`, never hand-edited,
  // so they are exempt from lint/format rules (they'd only be reintroduced on regen).
  { ignores: ["src/db/database.types.ts"] },
  baseConfig,
  reactConfig,
  runtimeBoundaryConfig,
  eslintPluginAstro.configs["flat/recommended"],
  ...eslintPluginAstro.configs["flat/jsx-a11y-recommended"],
  astroConfig,
  eslintPluginPrettier,
);
